// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-core/rpc/ent/sysbanner"
)

// SysBanner is the model entity for the SysBanner schema.
type SysBanner struct {
	config `json:"-"`
	// ID of the ent.
	// UUID
	ID uuid.UUID `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Status 1: normal 2: ban | 状态 1 正常 2 禁用
	Status uint8 `json:"status,omitempty"`
	// Show At | 1: web| 2:miniprogram | 展示位置 1网页 2小程序
	ShowAt int8 `json:"show_at,omitempty"`
	// Url | 图片链接
	URL          string `json:"url,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysBanner) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysbanner.FieldStatus, sysbanner.FieldShowAt:
			values[i] = new(sql.NullInt64)
		case sysbanner.FieldURL:
			values[i] = new(sql.NullString)
		case sysbanner.FieldCreatedAt, sysbanner.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case sysbanner.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysBanner fields.
func (sb *SysBanner) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysbanner.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				sb.ID = *value
			}
		case sysbanner.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sb.CreatedAt = value.Time
			}
		case sysbanner.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sb.UpdatedAt = value.Time
			}
		case sysbanner.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				sb.Status = uint8(value.Int64)
			}
		case sysbanner.FieldShowAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field show_at", values[i])
			} else if value.Valid {
				sb.ShowAt = int8(value.Int64)
			}
		case sysbanner.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				sb.URL = value.String
			}
		default:
			sb.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysBanner.
// This includes values selected through modifiers, order, etc.
func (sb *SysBanner) Value(name string) (ent.Value, error) {
	return sb.selectValues.Get(name)
}

// Update returns a builder for updating this SysBanner.
// Note that you need to call SysBanner.Unwrap() before calling this method if this SysBanner
// was returned from a transaction, and the transaction was committed or rolled back.
func (sb *SysBanner) Update() *SysBannerUpdateOne {
	return NewSysBannerClient(sb.config).UpdateOne(sb)
}

// Unwrap unwraps the SysBanner entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sb *SysBanner) Unwrap() *SysBanner {
	_tx, ok := sb.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysBanner is not a transactional entity")
	}
	sb.config.driver = _tx.drv
	return sb
}

// String implements the fmt.Stringer.
func (sb *SysBanner) String() string {
	var builder strings.Builder
	builder.WriteString("SysBanner(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sb.ID))
	builder.WriteString("created_at=")
	builder.WriteString(sb.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sb.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", sb.Status))
	builder.WriteString(", ")
	builder.WriteString("show_at=")
	builder.WriteString(fmt.Sprintf("%v", sb.ShowAt))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(sb.URL)
	builder.WriteByte(')')
	return builder.String()
}

// SysBanners is a parsable slice of SysBanner.
type SysBanners []*SysBanner
