// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-core/rpc/ent/predicate"
	"github.com/suyuan32/simple-admin-core/rpc/ent/sysbanner"
)

// SysBannerUpdate is the builder for updating SysBanner entities.
type SysBannerUpdate struct {
	config
	hooks     []Hook
	mutation  *SysBannerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SysBannerUpdate builder.
func (sbu *SysBannerUpdate) Where(ps ...predicate.SysBanner) *SysBannerUpdate {
	sbu.mutation.Where(ps...)
	return sbu
}

// SetUpdatedAt sets the "updated_at" field.
func (sbu *SysBannerUpdate) SetUpdatedAt(t time.Time) *SysBannerUpdate {
	sbu.mutation.SetUpdatedAt(t)
	return sbu
}

// SetStatus sets the "status" field.
func (sbu *SysBannerUpdate) SetStatus(u uint8) *SysBannerUpdate {
	sbu.mutation.ResetStatus()
	sbu.mutation.SetStatus(u)
	return sbu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sbu *SysBannerUpdate) SetNillableStatus(u *uint8) *SysBannerUpdate {
	if u != nil {
		sbu.SetStatus(*u)
	}
	return sbu
}

// AddStatus adds u to the "status" field.
func (sbu *SysBannerUpdate) AddStatus(u int8) *SysBannerUpdate {
	sbu.mutation.AddStatus(u)
	return sbu
}

// ClearStatus clears the value of the "status" field.
func (sbu *SysBannerUpdate) ClearStatus() *SysBannerUpdate {
	sbu.mutation.ClearStatus()
	return sbu
}

// SetShowAt sets the "show_at" field.
func (sbu *SysBannerUpdate) SetShowAt(i int8) *SysBannerUpdate {
	sbu.mutation.ResetShowAt()
	sbu.mutation.SetShowAt(i)
	return sbu
}

// SetNillableShowAt sets the "show_at" field if the given value is not nil.
func (sbu *SysBannerUpdate) SetNillableShowAt(i *int8) *SysBannerUpdate {
	if i != nil {
		sbu.SetShowAt(*i)
	}
	return sbu
}

// AddShowAt adds i to the "show_at" field.
func (sbu *SysBannerUpdate) AddShowAt(i int8) *SysBannerUpdate {
	sbu.mutation.AddShowAt(i)
	return sbu
}

// SetURL sets the "url" field.
func (sbu *SysBannerUpdate) SetURL(s string) *SysBannerUpdate {
	sbu.mutation.SetURL(s)
	return sbu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (sbu *SysBannerUpdate) SetNillableURL(s *string) *SysBannerUpdate {
	if s != nil {
		sbu.SetURL(*s)
	}
	return sbu
}

// Mutation returns the SysBannerMutation object of the builder.
func (sbu *SysBannerUpdate) Mutation() *SysBannerMutation {
	return sbu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sbu *SysBannerUpdate) Save(ctx context.Context) (int, error) {
	sbu.defaults()
	return withHooks(ctx, sbu.sqlSave, sbu.mutation, sbu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sbu *SysBannerUpdate) SaveX(ctx context.Context) int {
	affected, err := sbu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sbu *SysBannerUpdate) Exec(ctx context.Context) error {
	_, err := sbu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sbu *SysBannerUpdate) ExecX(ctx context.Context) {
	if err := sbu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sbu *SysBannerUpdate) defaults() {
	if _, ok := sbu.mutation.UpdatedAt(); !ok {
		v := sysbanner.UpdateDefaultUpdatedAt()
		sbu.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (sbu *SysBannerUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SysBannerUpdate {
	sbu.modifiers = append(sbu.modifiers, modifiers...)
	return sbu
}

func (sbu *SysBannerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysbanner.Table, sysbanner.Columns, sqlgraph.NewFieldSpec(sysbanner.FieldID, field.TypeUUID))
	if ps := sbu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sbu.mutation.UpdatedAt(); ok {
		_spec.SetField(sysbanner.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sbu.mutation.Status(); ok {
		_spec.SetField(sysbanner.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := sbu.mutation.AddedStatus(); ok {
		_spec.AddField(sysbanner.FieldStatus, field.TypeUint8, value)
	}
	if sbu.mutation.StatusCleared() {
		_spec.ClearField(sysbanner.FieldStatus, field.TypeUint8)
	}
	if value, ok := sbu.mutation.ShowAt(); ok {
		_spec.SetField(sysbanner.FieldShowAt, field.TypeInt8, value)
	}
	if value, ok := sbu.mutation.AddedShowAt(); ok {
		_spec.AddField(sysbanner.FieldShowAt, field.TypeInt8, value)
	}
	if value, ok := sbu.mutation.URL(); ok {
		_spec.SetField(sysbanner.FieldURL, field.TypeString, value)
	}
	_spec.AddModifiers(sbu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, sbu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysbanner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sbu.mutation.done = true
	return n, nil
}

// SysBannerUpdateOne is the builder for updating a single SysBanner entity.
type SysBannerUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SysBannerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (sbuo *SysBannerUpdateOne) SetUpdatedAt(t time.Time) *SysBannerUpdateOne {
	sbuo.mutation.SetUpdatedAt(t)
	return sbuo
}

// SetStatus sets the "status" field.
func (sbuo *SysBannerUpdateOne) SetStatus(u uint8) *SysBannerUpdateOne {
	sbuo.mutation.ResetStatus()
	sbuo.mutation.SetStatus(u)
	return sbuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sbuo *SysBannerUpdateOne) SetNillableStatus(u *uint8) *SysBannerUpdateOne {
	if u != nil {
		sbuo.SetStatus(*u)
	}
	return sbuo
}

// AddStatus adds u to the "status" field.
func (sbuo *SysBannerUpdateOne) AddStatus(u int8) *SysBannerUpdateOne {
	sbuo.mutation.AddStatus(u)
	return sbuo
}

// ClearStatus clears the value of the "status" field.
func (sbuo *SysBannerUpdateOne) ClearStatus() *SysBannerUpdateOne {
	sbuo.mutation.ClearStatus()
	return sbuo
}

// SetShowAt sets the "show_at" field.
func (sbuo *SysBannerUpdateOne) SetShowAt(i int8) *SysBannerUpdateOne {
	sbuo.mutation.ResetShowAt()
	sbuo.mutation.SetShowAt(i)
	return sbuo
}

// SetNillableShowAt sets the "show_at" field if the given value is not nil.
func (sbuo *SysBannerUpdateOne) SetNillableShowAt(i *int8) *SysBannerUpdateOne {
	if i != nil {
		sbuo.SetShowAt(*i)
	}
	return sbuo
}

// AddShowAt adds i to the "show_at" field.
func (sbuo *SysBannerUpdateOne) AddShowAt(i int8) *SysBannerUpdateOne {
	sbuo.mutation.AddShowAt(i)
	return sbuo
}

// SetURL sets the "url" field.
func (sbuo *SysBannerUpdateOne) SetURL(s string) *SysBannerUpdateOne {
	sbuo.mutation.SetURL(s)
	return sbuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (sbuo *SysBannerUpdateOne) SetNillableURL(s *string) *SysBannerUpdateOne {
	if s != nil {
		sbuo.SetURL(*s)
	}
	return sbuo
}

// Mutation returns the SysBannerMutation object of the builder.
func (sbuo *SysBannerUpdateOne) Mutation() *SysBannerMutation {
	return sbuo.mutation
}

// Where appends a list predicates to the SysBannerUpdate builder.
func (sbuo *SysBannerUpdateOne) Where(ps ...predicate.SysBanner) *SysBannerUpdateOne {
	sbuo.mutation.Where(ps...)
	return sbuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sbuo *SysBannerUpdateOne) Select(field string, fields ...string) *SysBannerUpdateOne {
	sbuo.fields = append([]string{field}, fields...)
	return sbuo
}

// Save executes the query and returns the updated SysBanner entity.
func (sbuo *SysBannerUpdateOne) Save(ctx context.Context) (*SysBanner, error) {
	sbuo.defaults()
	return withHooks(ctx, sbuo.sqlSave, sbuo.mutation, sbuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sbuo *SysBannerUpdateOne) SaveX(ctx context.Context) *SysBanner {
	node, err := sbuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sbuo *SysBannerUpdateOne) Exec(ctx context.Context) error {
	_, err := sbuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sbuo *SysBannerUpdateOne) ExecX(ctx context.Context) {
	if err := sbuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sbuo *SysBannerUpdateOne) defaults() {
	if _, ok := sbuo.mutation.UpdatedAt(); !ok {
		v := sysbanner.UpdateDefaultUpdatedAt()
		sbuo.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (sbuo *SysBannerUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SysBannerUpdateOne {
	sbuo.modifiers = append(sbuo.modifiers, modifiers...)
	return sbuo
}

func (sbuo *SysBannerUpdateOne) sqlSave(ctx context.Context) (_node *SysBanner, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysbanner.Table, sysbanner.Columns, sqlgraph.NewFieldSpec(sysbanner.FieldID, field.TypeUUID))
	id, ok := sbuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysBanner.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sbuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysbanner.FieldID)
		for _, f := range fields {
			if !sysbanner.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysbanner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sbuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sbuo.mutation.UpdatedAt(); ok {
		_spec.SetField(sysbanner.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sbuo.mutation.Status(); ok {
		_spec.SetField(sysbanner.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := sbuo.mutation.AddedStatus(); ok {
		_spec.AddField(sysbanner.FieldStatus, field.TypeUint8, value)
	}
	if sbuo.mutation.StatusCleared() {
		_spec.ClearField(sysbanner.FieldStatus, field.TypeUint8)
	}
	if value, ok := sbuo.mutation.ShowAt(); ok {
		_spec.SetField(sysbanner.FieldShowAt, field.TypeInt8, value)
	}
	if value, ok := sbuo.mutation.AddedShowAt(); ok {
		_spec.AddField(sysbanner.FieldShowAt, field.TypeInt8, value)
	}
	if value, ok := sbuo.mutation.URL(); ok {
		_spec.SetField(sysbanner.FieldURL, field.TypeString, value)
	}
	_spec.AddModifiers(sbuo.modifiers...)
	_node = &SysBanner{config: sbuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sbuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysbanner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sbuo.mutation.done = true
	return _node, nil
}
