// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-core/rpc/ent/predicate"
	"github.com/suyuan32/simple-admin-core/rpc/ent/sysbanner"
)

// SysBannerDelete is the builder for deleting a SysBanner entity.
type SysBannerDelete struct {
	config
	hooks    []Hook
	mutation *SysBannerMutation
}

// Where appends a list predicates to the SysBannerDelete builder.
func (sbd *SysBannerDelete) Where(ps ...predicate.SysBanner) *SysBannerDelete {
	sbd.mutation.Where(ps...)
	return sbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sbd *SysBannerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sbd.sqlExec, sbd.mutation, sbd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sbd *SysBannerDelete) ExecX(ctx context.Context) int {
	n, err := sbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sbd *SysBannerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sysbanner.Table, sqlgraph.NewFieldSpec(sysbanner.FieldID, field.TypeUUID))
	if ps := sbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sbd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sbd.mutation.done = true
	return affected, err
}

// SysBannerDeleteOne is the builder for deleting a single SysBanner entity.
type SysBannerDeleteOne struct {
	sbd *SysBannerDelete
}

// Where appends a list predicates to the SysBannerDelete builder.
func (sbdo *SysBannerDeleteOne) Where(ps ...predicate.SysBanner) *SysBannerDeleteOne {
	sbdo.sbd.mutation.Where(ps...)
	return sbdo
}

// Exec executes the deletion query.
func (sbdo *SysBannerDeleteOne) Exec(ctx context.Context) error {
	n, err := sbdo.sbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sysbanner.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sbdo *SysBannerDeleteOne) ExecX(ctx context.Context) {
	if err := sbdo.Exec(ctx); err != nil {
		panic(err)
	}
}
