// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-core/rpc/ent/sysbanner"
)

// SysBannerCreate is the builder for creating a SysBanner entity.
type SysBannerCreate struct {
	config
	mutation *SysBannerMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (sbc *SysBannerCreate) SetCreatedAt(t time.Time) *SysBannerCreate {
	sbc.mutation.SetCreatedAt(t)
	return sbc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sbc *SysBannerCreate) SetNillableCreatedAt(t *time.Time) *SysBannerCreate {
	if t != nil {
		sbc.SetCreatedAt(*t)
	}
	return sbc
}

// SetUpdatedAt sets the "updated_at" field.
func (sbc *SysBannerCreate) SetUpdatedAt(t time.Time) *SysBannerCreate {
	sbc.mutation.SetUpdatedAt(t)
	return sbc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sbc *SysBannerCreate) SetNillableUpdatedAt(t *time.Time) *SysBannerCreate {
	if t != nil {
		sbc.SetUpdatedAt(*t)
	}
	return sbc
}

// SetStatus sets the "status" field.
func (sbc *SysBannerCreate) SetStatus(u uint8) *SysBannerCreate {
	sbc.mutation.SetStatus(u)
	return sbc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sbc *SysBannerCreate) SetNillableStatus(u *uint8) *SysBannerCreate {
	if u != nil {
		sbc.SetStatus(*u)
	}
	return sbc
}

// SetShowAt sets the "show_at" field.
func (sbc *SysBannerCreate) SetShowAt(i int8) *SysBannerCreate {
	sbc.mutation.SetShowAt(i)
	return sbc
}

// SetURL sets the "url" field.
func (sbc *SysBannerCreate) SetURL(s string) *SysBannerCreate {
	sbc.mutation.SetURL(s)
	return sbc
}

// SetID sets the "id" field.
func (sbc *SysBannerCreate) SetID(u uuid.UUID) *SysBannerCreate {
	sbc.mutation.SetID(u)
	return sbc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sbc *SysBannerCreate) SetNillableID(u *uuid.UUID) *SysBannerCreate {
	if u != nil {
		sbc.SetID(*u)
	}
	return sbc
}

// Mutation returns the SysBannerMutation object of the builder.
func (sbc *SysBannerCreate) Mutation() *SysBannerMutation {
	return sbc.mutation
}

// Save creates the SysBanner in the database.
func (sbc *SysBannerCreate) Save(ctx context.Context) (*SysBanner, error) {
	sbc.defaults()
	return withHooks(ctx, sbc.sqlSave, sbc.mutation, sbc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sbc *SysBannerCreate) SaveX(ctx context.Context) *SysBanner {
	v, err := sbc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sbc *SysBannerCreate) Exec(ctx context.Context) error {
	_, err := sbc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sbc *SysBannerCreate) ExecX(ctx context.Context) {
	if err := sbc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sbc *SysBannerCreate) defaults() {
	if _, ok := sbc.mutation.CreatedAt(); !ok {
		v := sysbanner.DefaultCreatedAt()
		sbc.mutation.SetCreatedAt(v)
	}
	if _, ok := sbc.mutation.UpdatedAt(); !ok {
		v := sysbanner.DefaultUpdatedAt()
		sbc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sbc.mutation.Status(); !ok {
		v := sysbanner.DefaultStatus
		sbc.mutation.SetStatus(v)
	}
	if _, ok := sbc.mutation.ID(); !ok {
		v := sysbanner.DefaultID()
		sbc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sbc *SysBannerCreate) check() error {
	if _, ok := sbc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysBanner.created_at"`)}
	}
	if _, ok := sbc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysBanner.updated_at"`)}
	}
	if _, ok := sbc.mutation.ShowAt(); !ok {
		return &ValidationError{Name: "show_at", err: errors.New(`ent: missing required field "SysBanner.show_at"`)}
	}
	if _, ok := sbc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "SysBanner.url"`)}
	}
	return nil
}

func (sbc *SysBannerCreate) sqlSave(ctx context.Context) (*SysBanner, error) {
	if err := sbc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sbc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sbc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sbc.mutation.id = &_node.ID
	sbc.mutation.done = true
	return _node, nil
}

func (sbc *SysBannerCreate) createSpec() (*SysBanner, *sqlgraph.CreateSpec) {
	var (
		_node = &SysBanner{config: sbc.config}
		_spec = sqlgraph.NewCreateSpec(sysbanner.Table, sqlgraph.NewFieldSpec(sysbanner.FieldID, field.TypeUUID))
	)
	if id, ok := sbc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sbc.mutation.CreatedAt(); ok {
		_spec.SetField(sysbanner.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sbc.mutation.UpdatedAt(); ok {
		_spec.SetField(sysbanner.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sbc.mutation.Status(); ok {
		_spec.SetField(sysbanner.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := sbc.mutation.ShowAt(); ok {
		_spec.SetField(sysbanner.FieldShowAt, field.TypeInt8, value)
		_node.ShowAt = value
	}
	if value, ok := sbc.mutation.URL(); ok {
		_spec.SetField(sysbanner.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	return _node, _spec
}

// SysBannerCreateBulk is the builder for creating many SysBanner entities in bulk.
type SysBannerCreateBulk struct {
	config
	err      error
	builders []*SysBannerCreate
}

// Save creates the SysBanner entities in the database.
func (sbcb *SysBannerCreateBulk) Save(ctx context.Context) ([]*SysBanner, error) {
	if sbcb.err != nil {
		return nil, sbcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sbcb.builders))
	nodes := make([]*SysBanner, len(sbcb.builders))
	mutators := make([]Mutator, len(sbcb.builders))
	for i := range sbcb.builders {
		func(i int, root context.Context) {
			builder := sbcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysBannerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sbcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sbcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sbcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sbcb *SysBannerCreateBulk) SaveX(ctx context.Context) []*SysBanner {
	v, err := sbcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sbcb *SysBannerCreateBulk) Exec(ctx context.Context) error {
	_, err := sbcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sbcb *SysBannerCreateBulk) ExecX(ctx context.Context) {
	if err := sbcb.Exec(ctx); err != nil {
		panic(err)
	}
}
