// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-core/rpc/ent/predicate"
	"github.com/suyuan32/simple-admin-core/rpc/ent/sysuserconfig"
)

// SysUserConfigQuery is the builder for querying SysUserConfig entities.
type SysUserConfigQuery struct {
	config
	ctx        *QueryContext
	order      []sysuserconfig.OrderOption
	inters     []Interceptor
	predicates []predicate.SysUserConfig
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SysUserConfigQuery builder.
func (sucq *SysUserConfigQuery) Where(ps ...predicate.SysUserConfig) *SysUserConfigQuery {
	sucq.predicates = append(sucq.predicates, ps...)
	return sucq
}

// Limit the number of records to be returned by this query.
func (sucq *SysUserConfigQuery) Limit(limit int) *SysUserConfigQuery {
	sucq.ctx.Limit = &limit
	return sucq
}

// Offset to start from.
func (sucq *SysUserConfigQuery) Offset(offset int) *SysUserConfigQuery {
	sucq.ctx.Offset = &offset
	return sucq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sucq *SysUserConfigQuery) Unique(unique bool) *SysUserConfigQuery {
	sucq.ctx.Unique = &unique
	return sucq
}

// Order specifies how the records should be ordered.
func (sucq *SysUserConfigQuery) Order(o ...sysuserconfig.OrderOption) *SysUserConfigQuery {
	sucq.order = append(sucq.order, o...)
	return sucq
}

// First returns the first SysUserConfig entity from the query.
// Returns a *NotFoundError when no SysUserConfig was found.
func (sucq *SysUserConfigQuery) First(ctx context.Context) (*SysUserConfig, error) {
	nodes, err := sucq.Limit(1).All(setContextOp(ctx, sucq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sysuserconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sucq *SysUserConfigQuery) FirstX(ctx context.Context) *SysUserConfig {
	node, err := sucq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SysUserConfig ID from the query.
// Returns a *NotFoundError when no SysUserConfig ID was found.
func (sucq *SysUserConfigQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sucq.Limit(1).IDs(setContextOp(ctx, sucq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sysuserconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sucq *SysUserConfigQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := sucq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SysUserConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SysUserConfig entity is found.
// Returns a *NotFoundError when no SysUserConfig entities are found.
func (sucq *SysUserConfigQuery) Only(ctx context.Context) (*SysUserConfig, error) {
	nodes, err := sucq.Limit(2).All(setContextOp(ctx, sucq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sysuserconfig.Label}
	default:
		return nil, &NotSingularError{sysuserconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sucq *SysUserConfigQuery) OnlyX(ctx context.Context) *SysUserConfig {
	node, err := sucq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SysUserConfig ID in the query.
// Returns a *NotSingularError when more than one SysUserConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (sucq *SysUserConfigQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sucq.Limit(2).IDs(setContextOp(ctx, sucq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sysuserconfig.Label}
	default:
		err = &NotSingularError{sysuserconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sucq *SysUserConfigQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := sucq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SysUserConfigs.
func (sucq *SysUserConfigQuery) All(ctx context.Context) ([]*SysUserConfig, error) {
	ctx = setContextOp(ctx, sucq.ctx, "All")
	if err := sucq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SysUserConfig, *SysUserConfigQuery]()
	return withInterceptors[[]*SysUserConfig](ctx, sucq, qr, sucq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sucq *SysUserConfigQuery) AllX(ctx context.Context) []*SysUserConfig {
	nodes, err := sucq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SysUserConfig IDs.
func (sucq *SysUserConfigQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if sucq.ctx.Unique == nil && sucq.path != nil {
		sucq.Unique(true)
	}
	ctx = setContextOp(ctx, sucq.ctx, "IDs")
	if err = sucq.Select(sysuserconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sucq *SysUserConfigQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := sucq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sucq *SysUserConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sucq.ctx, "Count")
	if err := sucq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sucq, querierCount[*SysUserConfigQuery](), sucq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sucq *SysUserConfigQuery) CountX(ctx context.Context) int {
	count, err := sucq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sucq *SysUserConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sucq.ctx, "Exist")
	switch _, err := sucq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sucq *SysUserConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := sucq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SysUserConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sucq *SysUserConfigQuery) Clone() *SysUserConfigQuery {
	if sucq == nil {
		return nil
	}
	return &SysUserConfigQuery{
		config:     sucq.config,
		ctx:        sucq.ctx.Clone(),
		order:      append([]sysuserconfig.OrderOption{}, sucq.order...),
		inters:     append([]Interceptor{}, sucq.inters...),
		predicates: append([]predicate.SysUserConfig{}, sucq.predicates...),
		// clone intermediate query.
		sql:  sucq.sql.Clone(),
		path: sucq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SysUserConfig.Query().
//		GroupBy(sysuserconfig.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sucq *SysUserConfigQuery) GroupBy(field string, fields ...string) *SysUserConfigGroupBy {
	sucq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SysUserConfigGroupBy{build: sucq}
	grbuild.flds = &sucq.ctx.Fields
	grbuild.label = sysuserconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SysUserConfig.Query().
//		Select(sysuserconfig.FieldCreatedAt).
//		Scan(ctx, &v)
func (sucq *SysUserConfigQuery) Select(fields ...string) *SysUserConfigSelect {
	sucq.ctx.Fields = append(sucq.ctx.Fields, fields...)
	sbuild := &SysUserConfigSelect{SysUserConfigQuery: sucq}
	sbuild.label = sysuserconfig.Label
	sbuild.flds, sbuild.scan = &sucq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SysUserConfigSelect configured with the given aggregations.
func (sucq *SysUserConfigQuery) Aggregate(fns ...AggregateFunc) *SysUserConfigSelect {
	return sucq.Select().Aggregate(fns...)
}

func (sucq *SysUserConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sucq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sucq); err != nil {
				return err
			}
		}
	}
	for _, f := range sucq.ctx.Fields {
		if !sysuserconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sucq.path != nil {
		prev, err := sucq.path(ctx)
		if err != nil {
			return err
		}
		sucq.sql = prev
	}
	return nil
}

func (sucq *SysUserConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SysUserConfig, error) {
	var (
		nodes = []*SysUserConfig{}
		_spec = sucq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SysUserConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SysUserConfig{config: sucq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(sucq.modifiers) > 0 {
		_spec.Modifiers = sucq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sucq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sucq *SysUserConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sucq.querySpec()
	if len(sucq.modifiers) > 0 {
		_spec.Modifiers = sucq.modifiers
	}
	_spec.Node.Columns = sucq.ctx.Fields
	if len(sucq.ctx.Fields) > 0 {
		_spec.Unique = sucq.ctx.Unique != nil && *sucq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sucq.driver, _spec)
}

func (sucq *SysUserConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sysuserconfig.Table, sysuserconfig.Columns, sqlgraph.NewFieldSpec(sysuserconfig.FieldID, field.TypeUUID))
	_spec.From = sucq.sql
	if unique := sucq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sucq.path != nil {
		_spec.Unique = true
	}
	if fields := sucq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysuserconfig.FieldID)
		for i := range fields {
			if fields[i] != sysuserconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sucq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sucq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sucq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sucq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sucq *SysUserConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sucq.driver.Dialect())
	t1 := builder.Table(sysuserconfig.Table)
	columns := sucq.ctx.Fields
	if len(columns) == 0 {
		columns = sysuserconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sucq.sql != nil {
		selector = sucq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sucq.ctx.Unique != nil && *sucq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range sucq.modifiers {
		m(selector)
	}
	for _, p := range sucq.predicates {
		p(selector)
	}
	for _, p := range sucq.order {
		p(selector)
	}
	if offset := sucq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sucq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sucq *SysUserConfigQuery) Modify(modifiers ...func(s *sql.Selector)) *SysUserConfigSelect {
	sucq.modifiers = append(sucq.modifiers, modifiers...)
	return sucq.Select()
}

// SysUserConfigGroupBy is the group-by builder for SysUserConfig entities.
type SysUserConfigGroupBy struct {
	selector
	build *SysUserConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sucgb *SysUserConfigGroupBy) Aggregate(fns ...AggregateFunc) *SysUserConfigGroupBy {
	sucgb.fns = append(sucgb.fns, fns...)
	return sucgb
}

// Scan applies the selector query and scans the result into the given value.
func (sucgb *SysUserConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sucgb.build.ctx, "GroupBy")
	if err := sucgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysUserConfigQuery, *SysUserConfigGroupBy](ctx, sucgb.build, sucgb, sucgb.build.inters, v)
}

func (sucgb *SysUserConfigGroupBy) sqlScan(ctx context.Context, root *SysUserConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sucgb.fns))
	for _, fn := range sucgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sucgb.flds)+len(sucgb.fns))
		for _, f := range *sucgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sucgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sucgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SysUserConfigSelect is the builder for selecting fields of SysUserConfig entities.
type SysUserConfigSelect struct {
	*SysUserConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sucs *SysUserConfigSelect) Aggregate(fns ...AggregateFunc) *SysUserConfigSelect {
	sucs.fns = append(sucs.fns, fns...)
	return sucs
}

// Scan applies the selector query and scans the result into the given value.
func (sucs *SysUserConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sucs.ctx, "Select")
	if err := sucs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysUserConfigQuery, *SysUserConfigSelect](ctx, sucs.SysUserConfigQuery, sucs, sucs.inters, v)
}

func (sucs *SysUserConfigSelect) sqlScan(ctx context.Context, root *SysUserConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sucs.fns))
	for _, fn := range sucs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sucs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sucs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sucs *SysUserConfigSelect) Modify(modifiers ...func(s *sql.Selector)) *SysUserConfigSelect {
	sucs.modifiers = append(sucs.modifiers, modifiers...)
	return sucs
}
