// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-core/rpc/ent/predicate"
	"github.com/suyuan32/simple-admin-core/rpc/ent/sysuserconfig"
)

// SysUserConfigUpdate is the builder for updating SysUserConfig entities.
type SysUserConfigUpdate struct {
	config
	hooks     []Hook
	mutation  *SysUserConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SysUserConfigUpdate builder.
func (sucu *SysUserConfigUpdate) Where(ps ...predicate.SysUserConfig) *SysUserConfigUpdate {
	sucu.mutation.Where(ps...)
	return sucu
}

// SetUpdatedAt sets the "updated_at" field.
func (sucu *SysUserConfigUpdate) SetUpdatedAt(t time.Time) *SysUserConfigUpdate {
	sucu.mutation.SetUpdatedAt(t)
	return sucu
}

// SetDeletedAt sets the "deleted_at" field.
func (sucu *SysUserConfigUpdate) SetDeletedAt(t time.Time) *SysUserConfigUpdate {
	sucu.mutation.SetDeletedAt(t)
	return sucu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sucu *SysUserConfigUpdate) SetNillableDeletedAt(t *time.Time) *SysUserConfigUpdate {
	if t != nil {
		sucu.SetDeletedAt(*t)
	}
	return sucu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (sucu *SysUserConfigUpdate) ClearDeletedAt() *SysUserConfigUpdate {
	sucu.mutation.ClearDeletedAt()
	return sucu
}

// SetAnonymous sets the "anonymous" field.
func (sucu *SysUserConfigUpdate) SetAnonymous(b bool) *SysUserConfigUpdate {
	sucu.mutation.SetAnonymous(b)
	return sucu
}

// SetNillableAnonymous sets the "anonymous" field if the given value is not nil.
func (sucu *SysUserConfigUpdate) SetNillableAnonymous(b *bool) *SysUserConfigUpdate {
	if b != nil {
		sucu.SetAnonymous(*b)
	}
	return sucu
}

// SetShowAnswer sets the "show_answer" field.
func (sucu *SysUserConfigUpdate) SetShowAnswer(b bool) *SysUserConfigUpdate {
	sucu.mutation.SetShowAnswer(b)
	return sucu
}

// SetNillableShowAnswer sets the "show_answer" field if the given value is not nil.
func (sucu *SysUserConfigUpdate) SetNillableShowAnswer(b *bool) *SysUserConfigUpdate {
	if b != nil {
		sucu.SetShowAnswer(*b)
	}
	return sucu
}

// SetShowAnalysis sets the "show_analysis" field.
func (sucu *SysUserConfigUpdate) SetShowAnalysis(b bool) *SysUserConfigUpdate {
	sucu.mutation.SetShowAnalysis(b)
	return sucu
}

// SetNillableShowAnalysis sets the "show_analysis" field if the given value is not nil.
func (sucu *SysUserConfigUpdate) SetNillableShowAnalysis(b *bool) *SysUserConfigUpdate {
	if b != nil {
		sucu.SetShowAnalysis(*b)
	}
	return sucu
}

// SetShowComment sets the "show_comment" field.
func (sucu *SysUserConfigUpdate) SetShowComment(b bool) *SysUserConfigUpdate {
	sucu.mutation.SetShowComment(b)
	return sucu
}

// SetNillableShowComment sets the "show_comment" field if the given value is not nil.
func (sucu *SysUserConfigUpdate) SetNillableShowComment(b *bool) *SysUserConfigUpdate {
	if b != nil {
		sucu.SetShowComment(*b)
	}
	return sucu
}

// SetStuid sets the "stuid" field.
func (sucu *SysUserConfigUpdate) SetStuid(i int32) *SysUserConfigUpdate {
	sucu.mutation.ResetStuid()
	sucu.mutation.SetStuid(i)
	return sucu
}

// SetNillableStuid sets the "stuid" field if the given value is not nil.
func (sucu *SysUserConfigUpdate) SetNillableStuid(i *int32) *SysUserConfigUpdate {
	if i != nil {
		sucu.SetStuid(*i)
	}
	return sucu
}

// AddStuid adds i to the "stuid" field.
func (sucu *SysUserConfigUpdate) AddStuid(i int32) *SysUserConfigUpdate {
	sucu.mutation.AddStuid(i)
	return sucu
}

// ClearStuid clears the value of the "stuid" field.
func (sucu *SysUserConfigUpdate) ClearStuid() *SysUserConfigUpdate {
	sucu.mutation.ClearStuid()
	return sucu
}

// SetInstitute sets the "institute" field.
func (sucu *SysUserConfigUpdate) SetInstitute(i int16) *SysUserConfigUpdate {
	sucu.mutation.ResetInstitute()
	sucu.mutation.SetInstitute(i)
	return sucu
}

// SetNillableInstitute sets the "institute" field if the given value is not nil.
func (sucu *SysUserConfigUpdate) SetNillableInstitute(i *int16) *SysUserConfigUpdate {
	if i != nil {
		sucu.SetInstitute(*i)
	}
	return sucu
}

// AddInstitute adds i to the "institute" field.
func (sucu *SysUserConfigUpdate) AddInstitute(i int16) *SysUserConfigUpdate {
	sucu.mutation.AddInstitute(i)
	return sucu
}

// ClearInstitute clears the value of the "institute" field.
func (sucu *SysUserConfigUpdate) ClearInstitute() *SysUserConfigUpdate {
	sucu.mutation.ClearInstitute()
	return sucu
}

// SetEmailIsCheck sets the "email_is_check" field.
func (sucu *SysUserConfigUpdate) SetEmailIsCheck(b bool) *SysUserConfigUpdate {
	sucu.mutation.SetEmailIsCheck(b)
	return sucu
}

// SetNillableEmailIsCheck sets the "email_is_check" field if the given value is not nil.
func (sucu *SysUserConfigUpdate) SetNillableEmailIsCheck(b *bool) *SysUserConfigUpdate {
	if b != nil {
		sucu.SetEmailIsCheck(*b)
	}
	return sucu
}

// SetPhoneIsCheck sets the "phone_is_check" field.
func (sucu *SysUserConfigUpdate) SetPhoneIsCheck(b bool) *SysUserConfigUpdate {
	sucu.mutation.SetPhoneIsCheck(b)
	return sucu
}

// SetNillablePhoneIsCheck sets the "phone_is_check" field if the given value is not nil.
func (sucu *SysUserConfigUpdate) SetNillablePhoneIsCheck(b *bool) *SysUserConfigUpdate {
	if b != nil {
		sucu.SetPhoneIsCheck(*b)
	}
	return sucu
}

// Mutation returns the SysUserConfigMutation object of the builder.
func (sucu *SysUserConfigUpdate) Mutation() *SysUserConfigMutation {
	return sucu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sucu *SysUserConfigUpdate) Save(ctx context.Context) (int, error) {
	if err := sucu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, sucu.sqlSave, sucu.mutation, sucu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sucu *SysUserConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := sucu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sucu *SysUserConfigUpdate) Exec(ctx context.Context) error {
	_, err := sucu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sucu *SysUserConfigUpdate) ExecX(ctx context.Context) {
	if err := sucu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sucu *SysUserConfigUpdate) defaults() error {
	if _, ok := sucu.mutation.UpdatedAt(); !ok {
		if sysuserconfig.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysuserconfig.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sysuserconfig.UpdateDefaultUpdatedAt()
		sucu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (sucu *SysUserConfigUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SysUserConfigUpdate {
	sucu.modifiers = append(sucu.modifiers, modifiers...)
	return sucu
}

func (sucu *SysUserConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysuserconfig.Table, sysuserconfig.Columns, sqlgraph.NewFieldSpec(sysuserconfig.FieldID, field.TypeUUID))
	if ps := sucu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sucu.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuserconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sucu.mutation.DeletedAt(); ok {
		_spec.SetField(sysuserconfig.FieldDeletedAt, field.TypeTime, value)
	}
	if sucu.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuserconfig.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := sucu.mutation.Anonymous(); ok {
		_spec.SetField(sysuserconfig.FieldAnonymous, field.TypeBool, value)
	}
	if value, ok := sucu.mutation.ShowAnswer(); ok {
		_spec.SetField(sysuserconfig.FieldShowAnswer, field.TypeBool, value)
	}
	if value, ok := sucu.mutation.ShowAnalysis(); ok {
		_spec.SetField(sysuserconfig.FieldShowAnalysis, field.TypeBool, value)
	}
	if value, ok := sucu.mutation.ShowComment(); ok {
		_spec.SetField(sysuserconfig.FieldShowComment, field.TypeBool, value)
	}
	if value, ok := sucu.mutation.Stuid(); ok {
		_spec.SetField(sysuserconfig.FieldStuid, field.TypeInt32, value)
	}
	if value, ok := sucu.mutation.AddedStuid(); ok {
		_spec.AddField(sysuserconfig.FieldStuid, field.TypeInt32, value)
	}
	if sucu.mutation.StuidCleared() {
		_spec.ClearField(sysuserconfig.FieldStuid, field.TypeInt32)
	}
	if value, ok := sucu.mutation.Institute(); ok {
		_spec.SetField(sysuserconfig.FieldInstitute, field.TypeInt16, value)
	}
	if value, ok := sucu.mutation.AddedInstitute(); ok {
		_spec.AddField(sysuserconfig.FieldInstitute, field.TypeInt16, value)
	}
	if sucu.mutation.InstituteCleared() {
		_spec.ClearField(sysuserconfig.FieldInstitute, field.TypeInt16)
	}
	if value, ok := sucu.mutation.EmailIsCheck(); ok {
		_spec.SetField(sysuserconfig.FieldEmailIsCheck, field.TypeBool, value)
	}
	if value, ok := sucu.mutation.PhoneIsCheck(); ok {
		_spec.SetField(sysuserconfig.FieldPhoneIsCheck, field.TypeBool, value)
	}
	_spec.AddModifiers(sucu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, sucu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuserconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sucu.mutation.done = true
	return n, nil
}

// SysUserConfigUpdateOne is the builder for updating a single SysUserConfig entity.
type SysUserConfigUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SysUserConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (sucuo *SysUserConfigUpdateOne) SetUpdatedAt(t time.Time) *SysUserConfigUpdateOne {
	sucuo.mutation.SetUpdatedAt(t)
	return sucuo
}

// SetDeletedAt sets the "deleted_at" field.
func (sucuo *SysUserConfigUpdateOne) SetDeletedAt(t time.Time) *SysUserConfigUpdateOne {
	sucuo.mutation.SetDeletedAt(t)
	return sucuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sucuo *SysUserConfigUpdateOne) SetNillableDeletedAt(t *time.Time) *SysUserConfigUpdateOne {
	if t != nil {
		sucuo.SetDeletedAt(*t)
	}
	return sucuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (sucuo *SysUserConfigUpdateOne) ClearDeletedAt() *SysUserConfigUpdateOne {
	sucuo.mutation.ClearDeletedAt()
	return sucuo
}

// SetAnonymous sets the "anonymous" field.
func (sucuo *SysUserConfigUpdateOne) SetAnonymous(b bool) *SysUserConfigUpdateOne {
	sucuo.mutation.SetAnonymous(b)
	return sucuo
}

// SetNillableAnonymous sets the "anonymous" field if the given value is not nil.
func (sucuo *SysUserConfigUpdateOne) SetNillableAnonymous(b *bool) *SysUserConfigUpdateOne {
	if b != nil {
		sucuo.SetAnonymous(*b)
	}
	return sucuo
}

// SetShowAnswer sets the "show_answer" field.
func (sucuo *SysUserConfigUpdateOne) SetShowAnswer(b bool) *SysUserConfigUpdateOne {
	sucuo.mutation.SetShowAnswer(b)
	return sucuo
}

// SetNillableShowAnswer sets the "show_answer" field if the given value is not nil.
func (sucuo *SysUserConfigUpdateOne) SetNillableShowAnswer(b *bool) *SysUserConfigUpdateOne {
	if b != nil {
		sucuo.SetShowAnswer(*b)
	}
	return sucuo
}

// SetShowAnalysis sets the "show_analysis" field.
func (sucuo *SysUserConfigUpdateOne) SetShowAnalysis(b bool) *SysUserConfigUpdateOne {
	sucuo.mutation.SetShowAnalysis(b)
	return sucuo
}

// SetNillableShowAnalysis sets the "show_analysis" field if the given value is not nil.
func (sucuo *SysUserConfigUpdateOne) SetNillableShowAnalysis(b *bool) *SysUserConfigUpdateOne {
	if b != nil {
		sucuo.SetShowAnalysis(*b)
	}
	return sucuo
}

// SetShowComment sets the "show_comment" field.
func (sucuo *SysUserConfigUpdateOne) SetShowComment(b bool) *SysUserConfigUpdateOne {
	sucuo.mutation.SetShowComment(b)
	return sucuo
}

// SetNillableShowComment sets the "show_comment" field if the given value is not nil.
func (sucuo *SysUserConfigUpdateOne) SetNillableShowComment(b *bool) *SysUserConfigUpdateOne {
	if b != nil {
		sucuo.SetShowComment(*b)
	}
	return sucuo
}

// SetStuid sets the "stuid" field.
func (sucuo *SysUserConfigUpdateOne) SetStuid(i int32) *SysUserConfigUpdateOne {
	sucuo.mutation.ResetStuid()
	sucuo.mutation.SetStuid(i)
	return sucuo
}

// SetNillableStuid sets the "stuid" field if the given value is not nil.
func (sucuo *SysUserConfigUpdateOne) SetNillableStuid(i *int32) *SysUserConfigUpdateOne {
	if i != nil {
		sucuo.SetStuid(*i)
	}
	return sucuo
}

// AddStuid adds i to the "stuid" field.
func (sucuo *SysUserConfigUpdateOne) AddStuid(i int32) *SysUserConfigUpdateOne {
	sucuo.mutation.AddStuid(i)
	return sucuo
}

// ClearStuid clears the value of the "stuid" field.
func (sucuo *SysUserConfigUpdateOne) ClearStuid() *SysUserConfigUpdateOne {
	sucuo.mutation.ClearStuid()
	return sucuo
}

// SetInstitute sets the "institute" field.
func (sucuo *SysUserConfigUpdateOne) SetInstitute(i int16) *SysUserConfigUpdateOne {
	sucuo.mutation.ResetInstitute()
	sucuo.mutation.SetInstitute(i)
	return sucuo
}

// SetNillableInstitute sets the "institute" field if the given value is not nil.
func (sucuo *SysUserConfigUpdateOne) SetNillableInstitute(i *int16) *SysUserConfigUpdateOne {
	if i != nil {
		sucuo.SetInstitute(*i)
	}
	return sucuo
}

// AddInstitute adds i to the "institute" field.
func (sucuo *SysUserConfigUpdateOne) AddInstitute(i int16) *SysUserConfigUpdateOne {
	sucuo.mutation.AddInstitute(i)
	return sucuo
}

// ClearInstitute clears the value of the "institute" field.
func (sucuo *SysUserConfigUpdateOne) ClearInstitute() *SysUserConfigUpdateOne {
	sucuo.mutation.ClearInstitute()
	return sucuo
}

// SetEmailIsCheck sets the "email_is_check" field.
func (sucuo *SysUserConfigUpdateOne) SetEmailIsCheck(b bool) *SysUserConfigUpdateOne {
	sucuo.mutation.SetEmailIsCheck(b)
	return sucuo
}

// SetNillableEmailIsCheck sets the "email_is_check" field if the given value is not nil.
func (sucuo *SysUserConfigUpdateOne) SetNillableEmailIsCheck(b *bool) *SysUserConfigUpdateOne {
	if b != nil {
		sucuo.SetEmailIsCheck(*b)
	}
	return sucuo
}

// SetPhoneIsCheck sets the "phone_is_check" field.
func (sucuo *SysUserConfigUpdateOne) SetPhoneIsCheck(b bool) *SysUserConfigUpdateOne {
	sucuo.mutation.SetPhoneIsCheck(b)
	return sucuo
}

// SetNillablePhoneIsCheck sets the "phone_is_check" field if the given value is not nil.
func (sucuo *SysUserConfigUpdateOne) SetNillablePhoneIsCheck(b *bool) *SysUserConfigUpdateOne {
	if b != nil {
		sucuo.SetPhoneIsCheck(*b)
	}
	return sucuo
}

// Mutation returns the SysUserConfigMutation object of the builder.
func (sucuo *SysUserConfigUpdateOne) Mutation() *SysUserConfigMutation {
	return sucuo.mutation
}

// Where appends a list predicates to the SysUserConfigUpdate builder.
func (sucuo *SysUserConfigUpdateOne) Where(ps ...predicate.SysUserConfig) *SysUserConfigUpdateOne {
	sucuo.mutation.Where(ps...)
	return sucuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sucuo *SysUserConfigUpdateOne) Select(field string, fields ...string) *SysUserConfigUpdateOne {
	sucuo.fields = append([]string{field}, fields...)
	return sucuo
}

// Save executes the query and returns the updated SysUserConfig entity.
func (sucuo *SysUserConfigUpdateOne) Save(ctx context.Context) (*SysUserConfig, error) {
	if err := sucuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, sucuo.sqlSave, sucuo.mutation, sucuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sucuo *SysUserConfigUpdateOne) SaveX(ctx context.Context) *SysUserConfig {
	node, err := sucuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sucuo *SysUserConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := sucuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sucuo *SysUserConfigUpdateOne) ExecX(ctx context.Context) {
	if err := sucuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sucuo *SysUserConfigUpdateOne) defaults() error {
	if _, ok := sucuo.mutation.UpdatedAt(); !ok {
		if sysuserconfig.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysuserconfig.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sysuserconfig.UpdateDefaultUpdatedAt()
		sucuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (sucuo *SysUserConfigUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SysUserConfigUpdateOne {
	sucuo.modifiers = append(sucuo.modifiers, modifiers...)
	return sucuo
}

func (sucuo *SysUserConfigUpdateOne) sqlSave(ctx context.Context) (_node *SysUserConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysuserconfig.Table, sysuserconfig.Columns, sqlgraph.NewFieldSpec(sysuserconfig.FieldID, field.TypeUUID))
	id, ok := sucuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysUserConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sucuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysuserconfig.FieldID)
		for _, f := range fields {
			if !sysuserconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysuserconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sucuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sucuo.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuserconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sucuo.mutation.DeletedAt(); ok {
		_spec.SetField(sysuserconfig.FieldDeletedAt, field.TypeTime, value)
	}
	if sucuo.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuserconfig.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := sucuo.mutation.Anonymous(); ok {
		_spec.SetField(sysuserconfig.FieldAnonymous, field.TypeBool, value)
	}
	if value, ok := sucuo.mutation.ShowAnswer(); ok {
		_spec.SetField(sysuserconfig.FieldShowAnswer, field.TypeBool, value)
	}
	if value, ok := sucuo.mutation.ShowAnalysis(); ok {
		_spec.SetField(sysuserconfig.FieldShowAnalysis, field.TypeBool, value)
	}
	if value, ok := sucuo.mutation.ShowComment(); ok {
		_spec.SetField(sysuserconfig.FieldShowComment, field.TypeBool, value)
	}
	if value, ok := sucuo.mutation.Stuid(); ok {
		_spec.SetField(sysuserconfig.FieldStuid, field.TypeInt32, value)
	}
	if value, ok := sucuo.mutation.AddedStuid(); ok {
		_spec.AddField(sysuserconfig.FieldStuid, field.TypeInt32, value)
	}
	if sucuo.mutation.StuidCleared() {
		_spec.ClearField(sysuserconfig.FieldStuid, field.TypeInt32)
	}
	if value, ok := sucuo.mutation.Institute(); ok {
		_spec.SetField(sysuserconfig.FieldInstitute, field.TypeInt16, value)
	}
	if value, ok := sucuo.mutation.AddedInstitute(); ok {
		_spec.AddField(sysuserconfig.FieldInstitute, field.TypeInt16, value)
	}
	if sucuo.mutation.InstituteCleared() {
		_spec.ClearField(sysuserconfig.FieldInstitute, field.TypeInt16)
	}
	if value, ok := sucuo.mutation.EmailIsCheck(); ok {
		_spec.SetField(sysuserconfig.FieldEmailIsCheck, field.TypeBool, value)
	}
	if value, ok := sucuo.mutation.PhoneIsCheck(); ok {
		_spec.SetField(sysuserconfig.FieldPhoneIsCheck, field.TypeBool, value)
	}
	_spec.AddModifiers(sucuo.modifiers...)
	_node = &SysUserConfig{config: sucuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sucuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuserconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sucuo.mutation.done = true
	return _node, nil
}
