// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-core/rpc/ent/sysuserconfig"
)

// SysUserConfigCreate is the builder for creating a SysUserConfig entity.
type SysUserConfigCreate struct {
	config
	mutation *SysUserConfigMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (succ *SysUserConfigCreate) SetCreatedAt(t time.Time) *SysUserConfigCreate {
	succ.mutation.SetCreatedAt(t)
	return succ
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (succ *SysUserConfigCreate) SetNillableCreatedAt(t *time.Time) *SysUserConfigCreate {
	if t != nil {
		succ.SetCreatedAt(*t)
	}
	return succ
}

// SetUpdatedAt sets the "updated_at" field.
func (succ *SysUserConfigCreate) SetUpdatedAt(t time.Time) *SysUserConfigCreate {
	succ.mutation.SetUpdatedAt(t)
	return succ
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (succ *SysUserConfigCreate) SetNillableUpdatedAt(t *time.Time) *SysUserConfigCreate {
	if t != nil {
		succ.SetUpdatedAt(*t)
	}
	return succ
}

// SetDeletedAt sets the "deleted_at" field.
func (succ *SysUserConfigCreate) SetDeletedAt(t time.Time) *SysUserConfigCreate {
	succ.mutation.SetDeletedAt(t)
	return succ
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (succ *SysUserConfigCreate) SetNillableDeletedAt(t *time.Time) *SysUserConfigCreate {
	if t != nil {
		succ.SetDeletedAt(*t)
	}
	return succ
}

// SetAnonymous sets the "anonymous" field.
func (succ *SysUserConfigCreate) SetAnonymous(b bool) *SysUserConfigCreate {
	succ.mutation.SetAnonymous(b)
	return succ
}

// SetShowAnswer sets the "show_answer" field.
func (succ *SysUserConfigCreate) SetShowAnswer(b bool) *SysUserConfigCreate {
	succ.mutation.SetShowAnswer(b)
	return succ
}

// SetShowAnalysis sets the "show_analysis" field.
func (succ *SysUserConfigCreate) SetShowAnalysis(b bool) *SysUserConfigCreate {
	succ.mutation.SetShowAnalysis(b)
	return succ
}

// SetShowComment sets the "show_comment" field.
func (succ *SysUserConfigCreate) SetShowComment(b bool) *SysUserConfigCreate {
	succ.mutation.SetShowComment(b)
	return succ
}

// SetStuid sets the "stuid" field.
func (succ *SysUserConfigCreate) SetStuid(i int32) *SysUserConfigCreate {
	succ.mutation.SetStuid(i)
	return succ
}

// SetNillableStuid sets the "stuid" field if the given value is not nil.
func (succ *SysUserConfigCreate) SetNillableStuid(i *int32) *SysUserConfigCreate {
	if i != nil {
		succ.SetStuid(*i)
	}
	return succ
}

// SetInstitute sets the "institute" field.
func (succ *SysUserConfigCreate) SetInstitute(i int16) *SysUserConfigCreate {
	succ.mutation.SetInstitute(i)
	return succ
}

// SetNillableInstitute sets the "institute" field if the given value is not nil.
func (succ *SysUserConfigCreate) SetNillableInstitute(i *int16) *SysUserConfigCreate {
	if i != nil {
		succ.SetInstitute(*i)
	}
	return succ
}

// SetEmailIsCheck sets the "email_is_check" field.
func (succ *SysUserConfigCreate) SetEmailIsCheck(b bool) *SysUserConfigCreate {
	succ.mutation.SetEmailIsCheck(b)
	return succ
}

// SetPhoneIsCheck sets the "phone_is_check" field.
func (succ *SysUserConfigCreate) SetPhoneIsCheck(b bool) *SysUserConfigCreate {
	succ.mutation.SetPhoneIsCheck(b)
	return succ
}

// SetID sets the "id" field.
func (succ *SysUserConfigCreate) SetID(u uuid.UUID) *SysUserConfigCreate {
	succ.mutation.SetID(u)
	return succ
}

// SetNillableID sets the "id" field if the given value is not nil.
func (succ *SysUserConfigCreate) SetNillableID(u *uuid.UUID) *SysUserConfigCreate {
	if u != nil {
		succ.SetID(*u)
	}
	return succ
}

// Mutation returns the SysUserConfigMutation object of the builder.
func (succ *SysUserConfigCreate) Mutation() *SysUserConfigMutation {
	return succ.mutation
}

// Save creates the SysUserConfig in the database.
func (succ *SysUserConfigCreate) Save(ctx context.Context) (*SysUserConfig, error) {
	if err := succ.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, succ.sqlSave, succ.mutation, succ.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (succ *SysUserConfigCreate) SaveX(ctx context.Context) *SysUserConfig {
	v, err := succ.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (succ *SysUserConfigCreate) Exec(ctx context.Context) error {
	_, err := succ.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (succ *SysUserConfigCreate) ExecX(ctx context.Context) {
	if err := succ.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (succ *SysUserConfigCreate) defaults() error {
	if _, ok := succ.mutation.CreatedAt(); !ok {
		if sysuserconfig.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysuserconfig.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sysuserconfig.DefaultCreatedAt()
		succ.mutation.SetCreatedAt(v)
	}
	if _, ok := succ.mutation.UpdatedAt(); !ok {
		if sysuserconfig.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysuserconfig.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sysuserconfig.DefaultUpdatedAt()
		succ.mutation.SetUpdatedAt(v)
	}
	if _, ok := succ.mutation.ID(); !ok {
		if sysuserconfig.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized sysuserconfig.DefaultID (forgotten import ent/runtime?)")
		}
		v := sysuserconfig.DefaultID()
		succ.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (succ *SysUserConfigCreate) check() error {
	if _, ok := succ.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysUserConfig.created_at"`)}
	}
	if _, ok := succ.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysUserConfig.updated_at"`)}
	}
	if _, ok := succ.mutation.Anonymous(); !ok {
		return &ValidationError{Name: "anonymous", err: errors.New(`ent: missing required field "SysUserConfig.anonymous"`)}
	}
	if _, ok := succ.mutation.ShowAnswer(); !ok {
		return &ValidationError{Name: "show_answer", err: errors.New(`ent: missing required field "SysUserConfig.show_answer"`)}
	}
	if _, ok := succ.mutation.ShowAnalysis(); !ok {
		return &ValidationError{Name: "show_analysis", err: errors.New(`ent: missing required field "SysUserConfig.show_analysis"`)}
	}
	if _, ok := succ.mutation.ShowComment(); !ok {
		return &ValidationError{Name: "show_comment", err: errors.New(`ent: missing required field "SysUserConfig.show_comment"`)}
	}
	if _, ok := succ.mutation.EmailIsCheck(); !ok {
		return &ValidationError{Name: "email_is_check", err: errors.New(`ent: missing required field "SysUserConfig.email_is_check"`)}
	}
	if _, ok := succ.mutation.PhoneIsCheck(); !ok {
		return &ValidationError{Name: "phone_is_check", err: errors.New(`ent: missing required field "SysUserConfig.phone_is_check"`)}
	}
	return nil
}

func (succ *SysUserConfigCreate) sqlSave(ctx context.Context) (*SysUserConfig, error) {
	if err := succ.check(); err != nil {
		return nil, err
	}
	_node, _spec := succ.createSpec()
	if err := sqlgraph.CreateNode(ctx, succ.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	succ.mutation.id = &_node.ID
	succ.mutation.done = true
	return _node, nil
}

func (succ *SysUserConfigCreate) createSpec() (*SysUserConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &SysUserConfig{config: succ.config}
		_spec = sqlgraph.NewCreateSpec(sysuserconfig.Table, sqlgraph.NewFieldSpec(sysuserconfig.FieldID, field.TypeUUID))
	)
	if id, ok := succ.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := succ.mutation.CreatedAt(); ok {
		_spec.SetField(sysuserconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := succ.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuserconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := succ.mutation.DeletedAt(); ok {
		_spec.SetField(sysuserconfig.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := succ.mutation.Anonymous(); ok {
		_spec.SetField(sysuserconfig.FieldAnonymous, field.TypeBool, value)
		_node.Anonymous = value
	}
	if value, ok := succ.mutation.ShowAnswer(); ok {
		_spec.SetField(sysuserconfig.FieldShowAnswer, field.TypeBool, value)
		_node.ShowAnswer = value
	}
	if value, ok := succ.mutation.ShowAnalysis(); ok {
		_spec.SetField(sysuserconfig.FieldShowAnalysis, field.TypeBool, value)
		_node.ShowAnalysis = value
	}
	if value, ok := succ.mutation.ShowComment(); ok {
		_spec.SetField(sysuserconfig.FieldShowComment, field.TypeBool, value)
		_node.ShowComment = value
	}
	if value, ok := succ.mutation.Stuid(); ok {
		_spec.SetField(sysuserconfig.FieldStuid, field.TypeInt32, value)
		_node.Stuid = value
	}
	if value, ok := succ.mutation.Institute(); ok {
		_spec.SetField(sysuserconfig.FieldInstitute, field.TypeInt16, value)
		_node.Institute = value
	}
	if value, ok := succ.mutation.EmailIsCheck(); ok {
		_spec.SetField(sysuserconfig.FieldEmailIsCheck, field.TypeBool, value)
		_node.EmailIsCheck = value
	}
	if value, ok := succ.mutation.PhoneIsCheck(); ok {
		_spec.SetField(sysuserconfig.FieldPhoneIsCheck, field.TypeBool, value)
		_node.PhoneIsCheck = value
	}
	return _node, _spec
}

// SysUserConfigCreateBulk is the builder for creating many SysUserConfig entities in bulk.
type SysUserConfigCreateBulk struct {
	config
	err      error
	builders []*SysUserConfigCreate
}

// Save creates the SysUserConfig entities in the database.
func (succb *SysUserConfigCreateBulk) Save(ctx context.Context) ([]*SysUserConfig, error) {
	if succb.err != nil {
		return nil, succb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(succb.builders))
	nodes := make([]*SysUserConfig, len(succb.builders))
	mutators := make([]Mutator, len(succb.builders))
	for i := range succb.builders {
		func(i int, root context.Context) {
			builder := succb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysUserConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, succb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, succb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, succb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (succb *SysUserConfigCreateBulk) SaveX(ctx context.Context) []*SysUserConfig {
	v, err := succb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (succb *SysUserConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := succb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (succb *SysUserConfigCreateBulk) ExecX(ctx context.Context) {
	if err := succb.Exec(ctx); err != nil {
		panic(err)
	}
}
