// Code generated by ent, DO NOT EDIT.

package sysbanner

import (
	"time"

	"entgo.io/ent/dialect/sql"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-core/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldUpdatedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldStatus, v))
}

// ShowAt applies equality check predicate on the "show_at" field. It's identical to ShowAtEQ.
func ShowAt(v int8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldShowAt, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLTE(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.SysBanner {
	return predicate.SysBanner(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNotNull(FieldStatus))
}

// ShowAtEQ applies the EQ predicate on the "show_at" field.
func ShowAtEQ(v int8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldShowAt, v))
}

// ShowAtNEQ applies the NEQ predicate on the "show_at" field.
func ShowAtNEQ(v int8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNEQ(FieldShowAt, v))
}

// ShowAtIn applies the In predicate on the "show_at" field.
func ShowAtIn(vs ...int8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldIn(FieldShowAt, vs...))
}

// ShowAtNotIn applies the NotIn predicate on the "show_at" field.
func ShowAtNotIn(vs ...int8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNotIn(FieldShowAt, vs...))
}

// ShowAtGT applies the GT predicate on the "show_at" field.
func ShowAtGT(v int8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGT(FieldShowAt, v))
}

// ShowAtGTE applies the GTE predicate on the "show_at" field.
func ShowAtGTE(v int8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGTE(FieldShowAt, v))
}

// ShowAtLT applies the LT predicate on the "show_at" field.
func ShowAtLT(v int8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLT(FieldShowAt, v))
}

// ShowAtLTE applies the LTE predicate on the "show_at" field.
func ShowAtLTE(v int8) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLTE(FieldShowAt, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.SysBanner {
	return predicate.SysBanner(sql.FieldContainsFold(FieldURL, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysBanner) predicate.SysBanner {
	return predicate.SysBanner(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysBanner) predicate.SysBanner {
	return predicate.SysBanner(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysBanner) predicate.SysBanner {
	return predicate.SysBanner(sql.NotPredicates(p))
}
