// Code generated by ent, DO NOT EDIT.

package sysuserconfig

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	uuid "github.com/gofrs/uuid/v5"
)

const (
	// Label holds the string label denoting the sysuserconfig type in the database.
	Label = "sys_user_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldAnonymous holds the string denoting the anonymous field in the database.
	FieldAnonymous = "anonymous"
	// FieldShowAnswer holds the string denoting the show_answer field in the database.
	FieldShowAnswer = "show_answer"
	// FieldShowAnalysis holds the string denoting the show_analysis field in the database.
	FieldShowAnalysis = "show_analysis"
	// FieldShowComment holds the string denoting the show_comment field in the database.
	FieldShowComment = "show_comment"
	// FieldStuid holds the string denoting the stuid field in the database.
	FieldStuid = "stuid"
	// FieldInstitute holds the string denoting the institute field in the database.
	FieldInstitute = "institute"
	// FieldEmailIsCheck holds the string denoting the email_is_check field in the database.
	FieldEmailIsCheck = "email_is_check"
	// FieldPhoneIsCheck holds the string denoting the phone_is_check field in the database.
	FieldPhoneIsCheck = "phone_is_check"
	// Table holds the table name of the sysuserconfig in the database.
	Table = "sys_user_configs"
)

// Columns holds all SQL columns for sysuserconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldAnonymous,
	FieldShowAnswer,
	FieldShowAnalysis,
	FieldShowComment,
	FieldStuid,
	FieldInstitute,
	FieldEmailIsCheck,
	FieldPhoneIsCheck,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/suyuan32/simple-admin-core/rpc/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SysUserConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByAnonymous orders the results by the anonymous field.
func ByAnonymous(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnonymous, opts...).ToFunc()
}

// ByShowAnswer orders the results by the show_answer field.
func ByShowAnswer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShowAnswer, opts...).ToFunc()
}

// ByShowAnalysis orders the results by the show_analysis field.
func ByShowAnalysis(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShowAnalysis, opts...).ToFunc()
}

// ByShowComment orders the results by the show_comment field.
func ByShowComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShowComment, opts...).ToFunc()
}

// ByStuid orders the results by the stuid field.
func ByStuid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStuid, opts...).ToFunc()
}

// ByInstitute orders the results by the institute field.
func ByInstitute(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstitute, opts...).ToFunc()
}

// ByEmailIsCheck orders the results by the email_is_check field.
func ByEmailIsCheck(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailIsCheck, opts...).ToFunc()
}

// ByPhoneIsCheck orders the results by the phone_is_check field.
func ByPhoneIsCheck(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhoneIsCheck, opts...).ToFunc()
}
