// Code generated by ent, DO NOT EDIT.

package sysuserconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-core/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldDeletedAt, v))
}

// Anonymous applies equality check predicate on the "anonymous" field. It's identical to AnonymousEQ.
func Anonymous(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldAnonymous, v))
}

// ShowAnswer applies equality check predicate on the "show_answer" field. It's identical to ShowAnswerEQ.
func ShowAnswer(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldShowAnswer, v))
}

// ShowAnalysis applies equality check predicate on the "show_analysis" field. It's identical to ShowAnalysisEQ.
func ShowAnalysis(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldShowAnalysis, v))
}

// ShowComment applies equality check predicate on the "show_comment" field. It's identical to ShowCommentEQ.
func ShowComment(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldShowComment, v))
}

// Stuid applies equality check predicate on the "stuid" field. It's identical to StuidEQ.
func Stuid(v int32) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldStuid, v))
}

// Institute applies equality check predicate on the "institute" field. It's identical to InstituteEQ.
func Institute(v int16) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldInstitute, v))
}

// EmailIsCheck applies equality check predicate on the "email_is_check" field. It's identical to EmailIsCheckEQ.
func EmailIsCheck(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldEmailIsCheck, v))
}

// PhoneIsCheck applies equality check predicate on the "phone_is_check" field. It's identical to PhoneIsCheckEQ.
func PhoneIsCheck(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldPhoneIsCheck, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNotNull(FieldDeletedAt))
}

// AnonymousEQ applies the EQ predicate on the "anonymous" field.
func AnonymousEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldAnonymous, v))
}

// AnonymousNEQ applies the NEQ predicate on the "anonymous" field.
func AnonymousNEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldAnonymous, v))
}

// ShowAnswerEQ applies the EQ predicate on the "show_answer" field.
func ShowAnswerEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldShowAnswer, v))
}

// ShowAnswerNEQ applies the NEQ predicate on the "show_answer" field.
func ShowAnswerNEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldShowAnswer, v))
}

// ShowAnalysisEQ applies the EQ predicate on the "show_analysis" field.
func ShowAnalysisEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldShowAnalysis, v))
}

// ShowAnalysisNEQ applies the NEQ predicate on the "show_analysis" field.
func ShowAnalysisNEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldShowAnalysis, v))
}

// ShowCommentEQ applies the EQ predicate on the "show_comment" field.
func ShowCommentEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldShowComment, v))
}

// ShowCommentNEQ applies the NEQ predicate on the "show_comment" field.
func ShowCommentNEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldShowComment, v))
}

// StuidEQ applies the EQ predicate on the "stuid" field.
func StuidEQ(v int32) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldStuid, v))
}

// StuidNEQ applies the NEQ predicate on the "stuid" field.
func StuidNEQ(v int32) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldStuid, v))
}

// StuidIn applies the In predicate on the "stuid" field.
func StuidIn(vs ...int32) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldIn(FieldStuid, vs...))
}

// StuidNotIn applies the NotIn predicate on the "stuid" field.
func StuidNotIn(vs ...int32) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNotIn(FieldStuid, vs...))
}

// StuidGT applies the GT predicate on the "stuid" field.
func StuidGT(v int32) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGT(FieldStuid, v))
}

// StuidGTE applies the GTE predicate on the "stuid" field.
func StuidGTE(v int32) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGTE(FieldStuid, v))
}

// StuidLT applies the LT predicate on the "stuid" field.
func StuidLT(v int32) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLT(FieldStuid, v))
}

// StuidLTE applies the LTE predicate on the "stuid" field.
func StuidLTE(v int32) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLTE(FieldStuid, v))
}

// StuidIsNil applies the IsNil predicate on the "stuid" field.
func StuidIsNil() predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldIsNull(FieldStuid))
}

// StuidNotNil applies the NotNil predicate on the "stuid" field.
func StuidNotNil() predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNotNull(FieldStuid))
}

// InstituteEQ applies the EQ predicate on the "institute" field.
func InstituteEQ(v int16) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldInstitute, v))
}

// InstituteNEQ applies the NEQ predicate on the "institute" field.
func InstituteNEQ(v int16) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldInstitute, v))
}

// InstituteIn applies the In predicate on the "institute" field.
func InstituteIn(vs ...int16) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldIn(FieldInstitute, vs...))
}

// InstituteNotIn applies the NotIn predicate on the "institute" field.
func InstituteNotIn(vs ...int16) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNotIn(FieldInstitute, vs...))
}

// InstituteGT applies the GT predicate on the "institute" field.
func InstituteGT(v int16) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGT(FieldInstitute, v))
}

// InstituteGTE applies the GTE predicate on the "institute" field.
func InstituteGTE(v int16) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldGTE(FieldInstitute, v))
}

// InstituteLT applies the LT predicate on the "institute" field.
func InstituteLT(v int16) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLT(FieldInstitute, v))
}

// InstituteLTE applies the LTE predicate on the "institute" field.
func InstituteLTE(v int16) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldLTE(FieldInstitute, v))
}

// InstituteIsNil applies the IsNil predicate on the "institute" field.
func InstituteIsNil() predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldIsNull(FieldInstitute))
}

// InstituteNotNil applies the NotNil predicate on the "institute" field.
func InstituteNotNil() predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNotNull(FieldInstitute))
}

// EmailIsCheckEQ applies the EQ predicate on the "email_is_check" field.
func EmailIsCheckEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldEmailIsCheck, v))
}

// EmailIsCheckNEQ applies the NEQ predicate on the "email_is_check" field.
func EmailIsCheckNEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldEmailIsCheck, v))
}

// PhoneIsCheckEQ applies the EQ predicate on the "phone_is_check" field.
func PhoneIsCheckEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldEQ(FieldPhoneIsCheck, v))
}

// PhoneIsCheckNEQ applies the NEQ predicate on the "phone_is_check" field.
func PhoneIsCheckNEQ(v bool) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.FieldNEQ(FieldPhoneIsCheck, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysUserConfig) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysUserConfig) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysUserConfig) predicate.SysUserConfig {
	return predicate.SysUserConfig(sql.NotPredicates(p))
}
